# Generated by Django 3.0.7 on 2020-06-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('fabricante', models.TextField()),
                ('serie', models.CharField(max_length=16)),
            ],
        ),
    ]
