# Generated by Django 3.0.7 on 2020-06-14 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0003_camera'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Camera',
            new_name='Post',
        ),
    ]
