# Generated by Django 3.0.7 on 2020-06-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0004_auto_20200614_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fabricante',
            field=models.CharField(max_length=15),
        ),
    ]
