# Generated by Django 3.0.7 on 2020-06-16 13:52

import desafio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0006_camera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='camera',
        ),
        migrations.AddField(
            model_name='camera',
            name='fabricante',
            field=models.CharField(default='fabricante', max_length=50),
        ),
        migrations.AddField(
            model_name='camera',
            name='nome',
            field=models.CharField(default='nome', max_length=50),
        ),
        migrations.AddField(
            model_name='camera',
            name='serie',
            field=desafio.models.SerieField(default='serie', max_length=16),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
